# .circleci/config.yml

version: 2

jobs:

  build:

    parallelism: 4

    working_directory: ~/project-name

    docker:

      # this is important to use proper image with browsers support

      - image: circleci/ruby:2.4.2-node-browsers

        environment:

          PGHOST: 127.0.0.1

          PGUSER: project-name

          RAILS_ENV: test

      - image: circleci/postgres:9.4.12-alpine

        environment:

          POSTGRES_DB: project-name_test

          POSTGRES_PASSWORD: ""

          POSTGRES_USER: project-name

      - image: redis:3.2.7

    steps:

      - checkout


      # Restore bundle cache

      - type: cache-restore

        # remove space between { {

        key: project-name-{ { checksum "Gemfile.lock" }}


      # Bundle install dependencies

      - run: bundle install --path vendor/bundle


      # Store bundle cache

      - type: cache-save

        # remove space between { {

        key: project-name-{ { checksum "Gemfile.lock" }}

        paths:

          - vendor/bundle


      # Prepare .env, useful if you use dotenv gem

      - run: cp .env.example .env

      # Database setup

      - run: bundle exec rake db:create

      - run: bundle exec rake db:schema:load


      # Run rspec in parallel

      - type: shell

        command: |

          bundle exec rspec --profile 10 \

                            --format RspecJunitFormatter \

                            --out /tmp/test-results/rspec.xml \

                            --format progress

      # Save artifacts

      - type: store_test_results

        path: /tmp/test-results